### ISSUE TITLE
Fails for packages with non standard directory structure

### ISSUE THREAD

**Issue by nikolay-borzov** [styfle/packagephobia#688] opened 2021-02-06 12:34 UTC
packagephobia.com fails for some packages (e.g. [@nikolay-borzov/torrent-clean](https://packagephobia.com/result?p=%40nikolay-borzov%2Ftorrent-clean)). 
I assume it happens because the package doesn't have `src` directory.

**Comment by styfle** [comment] 2021-02-06 16:33
It's not the filesystem, its one of the dependencies that requires git CLI instead of npm.

```
Error while executing:
> undefined ls-remote -h -t ssh://git@github.com/feross/http-node.git
```

Closing as a duplicate of #388

**Closed by styfle** 2021-02-06 16:33 UTC
Labels: wontfix
